#!/bin/bash
# ============================================
# Ansible MCP Server - Installation Script
# ============================================
# This script automates the installation process
# Run with: chmod +x install.sh && ./install.sh
# ============================================

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Emoji indicators
CHECK="✅"
CROSS="❌"
WARN="⚠️"
INFO="📦"

echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  Ansible MCP Server Installation${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""

# ===== Check Prerequisites =====
echo -e "${INFO} Checking prerequisites..."

# Check Docker
if ! command -v docker &> /dev/null; then
    echo -e "${CROSS} ${RED}Docker not found${NC}"
    echo "Please install Docker first: https://docs.docker.com/get-docker/"
    exit 1
fi
echo -e "${CHECK} Docker: $(docker --version | cut -d' ' -f3 | cut -d',' -f1)"

# Check Docker Compose
if ! docker compose version &> /dev/null; then
    echo -e "${CROSS} ${RED}Docker Compose not found${NC}"
    echo "Please install Docker Compose v2+"
    exit 1
fi
echo -e "${CHECK} Docker Compose: $(docker compose version --short)"

# Check Git
if ! command -v git &> /dev/null; then
    echo -e "${CROSS} ${RED}Git not found${NC}"
    echo "Please install Git"
    exit 1
fi
echo -e "${CHECK} Git: $(git --version | cut -d' ' -f3)"

echo ""

# ===== Create Directories =====
echo -e "${INFO} Creating directories..."
mkdir -p playbooks inventory logs templates
echo -e "${CHECK} Created: playbooks, inventory, logs, templates"

# ===== Create Inventory =====
if [ ! -f inventory/hosts ]; then
    cat > inventory/hosts << 'EOF'
[local]
localhost ansible_connection=local

[webservers]
# Add your servers here
# web1.example.com ansible_user=admin

[databases]
# db1.example.com ansible_user=admin
EOF
    echo -e "${CHECK} Created default inventory file"
else
    echo -e "${WARN} Inventory file exists, skipping"
fi

# ===== Create Environment File =====
echo ""
echo -e "${INFO} Setting up environment..."

if [ ! -f .env ]; then
    # Generate JWT secret
    JWT_SECRET=$(openssl rand -base64 32 2>/dev/null || head -c 32 /dev/urandom | base64)

    cat > .env << EOF
# Generated by install.sh on $(date)

# ===== REQUIRED =====
JWT_SECRET=${JWT_SECRET}
POSTGRES_PASSWORD=ansible_mcp_$(openssl rand -hex 8 2>/dev/null || head -c 8 /dev/urandom | xxd -p)
POSTGRES_USER=ansible_mcp
POSTGRES_DB=awx
WEB_DB_NAME=ansible_mcp

# ===== SECURITY =====
VAULT_ROOT_TOKEN=dev-token-$(openssl rand -hex 8 2>/dev/null || head -c 8 /dev/urandom | xxd -p)
AWX_SECRET_KEY=$(openssl rand -hex 16 2>/dev/null || head -c 16 /dev/urandom | xxd -p)
GITLAB_ROOT_PASSWORD=gitlab-$(openssl rand -hex 8 2>/dev/null || head -c 8 /dev/urandom | xxd -p)
GRAFANA_ADMIN_PASSWORD=grafana-$(openssl rand -hex 8 2>/dev/null || head -c 8 /dev/urandom | xxd -p)

# ===== AI PROVIDER =====
# Uncomment and set your API key
AI_PROVIDER=openai
AI_MODEL=gpt-4
# OPENAI_API_KEY=sk-your-key-here
# ANTHROPIC_API_KEY=your-key-here
# GEMINI_API_KEY=your-key-here

# ===== LOGGING =====
LOG_LEVEL=info
EOF

    echo -e "${CHECK} Created .env with generated secrets"
    echo -e "${WARN} ${YELLOW}IMPORTANT: Add your AI API key to .env${NC}"
else
    echo -e "${WARN} .env file exists, skipping"
fi

# ===== Determine Script and Source Directories =====
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
RELEASE_DIR="$( cd "$SCRIPT_DIR/.." && pwd )"
SRC_DIR="$RELEASE_DIR/src"

# Use docker-compose.yml from src directory
COMPOSE_FILE="$SRC_DIR/docker-compose.yml"
ENV_FILE="$RELEASE_DIR/.env"

if [ ! -f "$COMPOSE_FILE" ]; then
    echo -e "${CROSS} ${RED}docker-compose.yml not found at $COMPOSE_FILE${NC}"
    exit 1
fi

# Docker compose command with env file
DOCKER_COMPOSE="docker compose -f $COMPOSE_FILE --env-file $ENV_FILE"

# ===== Pull Docker Images =====
echo ""
echo -e "${INFO} Pulling Docker images (this may take a few minutes)..."
$DOCKER_COMPOSE pull

echo -e "${CHECK} Images pulled successfully"

# ===== Start Services =====
echo ""
echo -e "${INFO} Starting services..."

# Ask which configuration to use
echo ""
echo "Select installation type:"
echo "  1) Minimal (MCP + Redis + Vault + Postgres) - ~1GB RAM"
echo "  2) Standard (+ Prometheus + Grafana) - ~2GB RAM"
echo "  3) Full (+ GitLab + AWX) - ~8GB RAM"
echo ""
read -p "Enter choice [1-3, default: 1]: " INSTALL_TYPE

case ${INSTALL_TYPE:-1} in
    1)
        echo -e "${INFO} Starting minimal services..."
        $DOCKER_COMPOSE up -d ansible-mcp redis vault postgres
        ;;
    2)
        echo -e "${INFO} Starting standard services..."
        $DOCKER_COMPOSE up -d ansible-mcp redis vault postgres prometheus grafana
        ;;
    3)
        echo -e "${INFO} Starting full stack..."
        $DOCKER_COMPOSE up -d
        ;;
    *)
        echo -e "${CROSS} Invalid choice, starting minimal..."
        $DOCKER_COMPOSE up -d ansible-mcp redis vault postgres
        ;;
esac

# ===== Wait for Services =====
echo ""
echo -e "${INFO} Waiting for services to start..."
sleep 10

# ===== Verify Installation =====
echo ""
echo -e "${INFO} Verifying installation..."

# Check MCP server
if curl -s http://localhost:9090/health > /dev/null 2>&1; then
    echo -e "${CHECK} MCP Server is running"
else
    echo -e "${WARN} MCP Server may still be starting..."
fi

# Check Redis
if $DOCKER_COMPOSE exec -T redis redis-cli ping 2>/dev/null | grep -q PONG; then
    echo -e "${CHECK} Redis is running"
else
    echo -e "${WARN} Redis may still be starting..."
fi

# ===== Print Summary =====
echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  Installation Complete!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo "Services:"
$DOCKER_COMPOSE ps --format "table {{.Name}}\t{{.Status}}\t{{.Ports}}" 2>/dev/null || $DOCKER_COMPOSE ps
echo ""
echo "Access URLs:"
echo "  - MCP Server:  http://localhost:3000"
echo "  - Health:      http://localhost:3000/health"
echo "  - Vault:       http://localhost:8200"

if [ "${INSTALL_TYPE:-1}" -ge 2 ]; then
    echo "  - Grafana:     http://localhost:3002"
    echo "  - Prometheus:  http://localhost:9090"
fi

if [ "${INSTALL_TYPE:-1}" -eq 3 ]; then
    echo "  - Web UI:      http://localhost:3001"
    echo "  - GitLab:      http://localhost:8080"
    echo "  - AWX:         http://localhost:8052"
fi

echo ""
echo "Next steps:"
echo "  1. Add your AI API key to .env"
echo "  2. Run: docker compose restart ansible-mcp"
echo "  3. Test: curl http://localhost:9090/health"
echo "  4. Read docs/quickstart.md"
echo ""
echo -e "${GREEN}Enjoy using Ansible MCP Server! 🚀${NC}"
